import{a as w,S as v,i as n}from"./assets/vendor-CauDeeDU.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))f(o);new MutationObserver(o=>{for(const i of o)if(i.type==="childList")for(const h of i.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&f(h)}).observe(document,{childList:!0,subtree:!0});function r(o){const i={};return o.integrity&&(i.integrity=o.integrity),o.referrerPolicy&&(i.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?i.credentials="include":o.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function f(o){if(o.ep)return;o.ep=!0;const i=r(o);fetch(o.href,i)}})();const S="51367924-123f738920e3f369a979532e9",q="https://pixabay.com/api/";async function p(t,e){const r={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await w.get(q,{params:r})).data}const l=document.querySelector(".gallery"),c=document.querySelector(".loader"),d=document.querySelector(".load-more"),u=document.querySelector(".loader-text"),b=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){if(!l)return;const e=t.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <ul>
            <li><h3>Likes</h3><p>${r.likes}</p></li>
            <li><h3>Views</h3><p>${r.views}</p></li>
            <li><h3>Comments</h3><p>${r.comments}</p></li>
            <li><h3>Downloads</h3><p>${r.downloads}</p></li>
          </ul>
        </div>
      </li>`).join("");l.insertAdjacentHTML("beforeend",e),b.refresh()}function $(){l&&(l.innerHTML="")}function x(){c&&c.classList.remove("hidden")}function R(){c&&c.classList.add("hidden")}function y(){d&&d.classList.remove("hidden")}function L(){d&&d.classList.add("hidden")}function B(){u&&u.classList.remove("hidden")}function M(){u&&u.classList.add("hidden")}const P=document.querySelector(".form"),E=document.querySelector(".load-more");let a="",s=1,m=0;P.addEventListener("submit",async t=>{if(t.preventDefault(),a=t.currentTarget.elements["search-text"].value.trim(),s=1,!a){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}L(),$(),B();try{const e=await p(a,s);m=Math.ceil(e.totalHits/15),e.hits.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(g(e.hits),s<m&&y())}catch(e){n.error({title:"Error",message:`Something went wrong during the search: ${e.message}`,position:"topRight"}),console.error(e)}finally{M()}});E.addEventListener("click",async()=>{s+=1,L(),x();try{const t=await p(a,s);g(t.hits),s<m?y():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),T()}catch(t){n.error({title:"Error",message:`Failed to load more images: ${t.message}`,position:"topRight"}),console.error(t)}finally{R()}});function T(){const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
